"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
import {DashboardWorkspace,type DashboardChart,type DashboardFilter} from "@/components/dashboard-workspace";import {AssessmentForm} from "@/components/forms/assessment-form";import {SaveToast} from "@/components/save-toast";import {loadAssessmentRecords} from "@/lib/actions/assessments";import {ASSESSMENT_PHASES,ASSESSMENT_TESTS,MONTHS,type AssessmentFilters} from "@/lib/assessments";import type {AssessmentChartRow,AssessmentSummary} from "@/lib/queries/assessments";
const COLUMNS=[{key:"record_id",label:"Record"},{key:"test_type",label:"Test"},{key:"phase",label:"Pre / Post"},{key:"beneficiary_id",label:"Beneficiary ID"},{key:"name_of_child",label:"Name"},{key:"assessment_date",label:"Date"}];
const CHARTS:[string,string,DashboardChart["kind"]][]=[["Rosenberg","Rosenberg responses by question","bar"],["Stirling","Stirling response scores by Pre / Post","bar"]];
export function AssessmentsView({filters,summary,charts,chartError}:{filters:AssessmentFilters;summary:AssessmentSummary|null;charts:AssessmentChartRow[];chartError?:string}){
const router=useRouter();const[,busy]=useState(false);const[savedAt,setSaved]=useState(0);const filterItems:DashboardFilter[]=[{key:"test",label:"Test type",value:filters.test,options:ASSESSMENT_TESTS},{key:"phase",label:"Pre / Post",value:filters.phase,options:ASSESSMENT_PHASES},{key:"month",label:"Month",value:filters.month,options:MONTHS}];
const chartData=CHARTS.map(([name,title,kind])=>({name,title,kind,rows:charts.filter(r=>r.chart_name===name).map(r=>({label:name==="Rosenberg"?`${r.label} · ${r.detail}`:`${r.label} · ${r.series}`,value:Number(r.value),series:r.series})),exportUrl:`/assessments/charts/export?chart=${name}`}));
return <><DashboardWorkspace title="Assessments" description="Response distributions from Rosenberg and Stirling records." path="/assessments" filters={filterItems} scores={[{label:"Assessments recorded",value:summary?.assessments_recorded??"—",tone:"pink"},{label:"Children assessed",value:summary?.children_assessed??"—",tone:"blue"},{label:"Pre / Post pairs",value:summary?.pre_post_pairs??"—",tone:"purple"}]} charts={chartData} addLabel="Assessment" addDescription="Add a new assessment for an existing beneficiary." addForm={close=><AssessmentForm close={close} onBusyChange={busy} onSaved={()=>{setSaved(Date.now());router.refresh();}}/>} recordColumns={COLUMNS} recordKey="record_id" recordsExportUrl="/assessments/export" loadRecords={loadAssessmentRecords} chartError={chartError}/><SaveToast savedAt={savedAt}/></>;
}
